server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shixun_blog?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver