server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.7.219:3306/ourblog?useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
